import nltk

# Download the NLTK words dataset (if not already downloaded)
nltk.download('words')

# Get the list of English words
from nltk.corpus import words
english_words = words.words()

# Filter for words over 3 letters
common_words_hard = [word for word in english_words if len(word) == 5]


# List of simple words
common_words_easy = [
    "apple",
    "table",
    "chair",
    "house",
    "store",
    "phone",
    "cloud",
    "black",
    "white",
    "green",
    "blue",
    "water",
    "music",
    "dance",
    "write",
    "light",
    "night",
    "stars",
    "beach",
    "heart",
    "smile",
    "laugh",
    "happy",
    "peace",
    "child",
    "woman",
    "money",
    "dream",
    "night",
    "birds",
    "grass",
    "lucky",
    "river",
    "peace",
    "paint",
    "beard",
    "dream",
    "party",
    "sound",
    "tiger",
    "table",
    "beach",
    "watch",
    "taste",
    "wrist",
    "smile",
    "faith",
    "sword",
    "swim",
    "kite",
    "moon",
    "road",
    "bike",
    "rose",
    "jump",
    "king",
    "bird",
    "fish",
    "ring",
    "fire",
    "star",
    "lion",
    "frog",
    "leaf",
    "tree",
    "book",
    "film",
    "game",
    "home",
    "love",
    "song",
    "tree",
    "wine",
    "rose",
    "gold",
    "mail",
    "lamp",
    "desk",
    "pen",
    "foot",
    "park",
    "moon",
    "salt",
    "road",
    "mint",
    "hill",
    "toes",
    "cats",
    "dogs",
    "blue",
    "lime",
    "flag",
    "cake",
    "ship",
    "flag",
    "nail",
    "heel",
    "skin",
    "hair",
    "pink",
    "milk",
    "star",
    "wind",
    "rock",
    "cave",
    "bass",
    "fire",
    "bird",
    "code",
    "corn",
    "film",
    "game",
    "food",
    "foot",
    "idea",
    "lake",
    "mind",
    "moon",
    "nose",
    "rose",
    "ring",
    "soap",
    "sock",
    "song",
    "star",
    "time",
    "baby",
    "book",
    "city",
    "club",
    "door",
    "face",
    "farm",
    "frog",
    "girl",
    "gold",
    "hand",
    "head",
    "home",
    "life",
    "lime",
    "mood",
    "nail",
    "rain",
    "rose",
    "seed",
    "ship",
    "star",
    "tree",
    "time",
    "word",
    "able",
    "acid",
    "arms",
    "bear",
    "bell",
    "blue",
    "bone",
    "book",
    "boot",
    "bowl",
    "cake",
    "card",
    "coat",
    "corn",
    "dark",
    "dirt",
    "door",
    "duck",
    "fair",
    "farm",
    "feet",
    "fish",
    "flag",
    "fog",
    "food",
    "foot",
    "game",
    "gate",
    "gift",
    "girl",
    "gold",
    "hair",
    "hand",
    "hat",
    "head",
    "heel",
    "hill",
    "home",
    "iron",
    "jump",
    "lamp",
    "lead",
    "leaf",
    "legs",
    "lion",
    "love",
    "luck",
    "mail",
    "mask",
    "moon",
    "nose",
    "oven",
    "palm",
    "pant",
    "pear",
    "pink",
    "pipe",
    "pond",
    "pool",
    "rain",
    "ring",
    "rope",
    "rose",
    "salt",
    "sand",
    "seed",
    "ship",
    "shoe",
    "skin",
    "sock",
    "star",
    "suit",
    "swim",
    "tail",
    "time",
    "toes",
    "tree",
    "vine",
    "wheat",
    "wheel",
    "woman",
    "world",
    "apple", "table", "chair", "house", "store", "phone", "cloud", "black", "white", "green",
    "blue", "water", "music", "dance", "write", "light", "night", "stars", "beach", "heart",
    "smile", "laugh", "happy", "peace", "child", "woman", "money", "dream", "night", "birds",
    "grass", "lucky", "river", "peace", "paint", "beard", "dream", "party", "sound", "tiger",
    "table", "beach", "watch", "taste", "wrist", "smile", "faith", "piano", "honor", "grape",
    "shine", "queen", "speak", "puppy", "ocean", "magic", "daisy", "angel", "smoke", "earth",
    "green", "candy", "peace", "black", "white", "water", "table", "sound", "apple", "table",
    "chair", "store", "phone", "cloud", "black", "green", "water", "music", "write", "light",
    "night", "stars", "beach", "smile", "happy", "peace", "child", "woman", "dream", "birds",
    "lucky", "river", "paint", "beard", "party", "tiger", "watch", "wrist", "faith", "piano",
    "honor", "grape", "shine", "queen", "speak", "puppy", "ocean", "magic", "daisy", "angel",
    "smoke", "earth", "candy", "beach"
]
